Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.hostname = "lb-debian-8-x64"
  config.vm.provision :shell, path: "https://raw.githubusercontent.com/lburgazzoli/lb-vagrant/master/resources/bootstrap.sh"
  config.vm.provider :virtualbox do |vb|
    vb.name   = "lb-debian-8-x64"
    vb.memory = 2048
    vb.cpus   = 2
  end
end
