Vagrant.configure("2") do |config|
  config.vm.box = "jansauer/centos7-core"
  config.vm.hostname = "lb-centos-7-0-x64"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, host: 8080, guest: 80
  config.vm.provider :virtualbox do |vb|
    vb.name   = "lb-centos-7_0-x64"
    vb.memory = 1024
    vb.cpus   = 4
  end
end
