Vagrant.configure("2") do |config|
  config.vm.box = "chef/centos-5.10-i386"
  config.vm.hostname = "lb-centos-5-10-x86"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, host: 8080, guest: 80
  config.vm.provider :virtualbox do |vb|
    vb.name   = "lb-centos-5_10-x86"
    vb.memory = 1024
    vb.cpus   = 2
  end
end
