Vagrant.configure("2") do |config|
  config.vm.box = "chef/debian-8.0"
  config.vm.hostname = "lb-debian-8-0-x64"
  config.vm.provision :shell, path: "https://raw.githubusercontent.com/lburgazzoli/lb-devops/master/lb-vagrant/resources/bootstrap.sh"
  config.vm.provider :virtualbox do |vb|
    vb.name   = "lb-debian-8_0-x64"
    vb.memory = 1024
    vb.cpus   = 4
  end
end
