Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "lb-ubuntu-14-04-x64"
  
  config.vm.provision :shell, path: "https://raw.githubusercontent.com/lburgazzoli/lb-devops/master/lb-vagrant/resources/bootstrap.sh"

  config.vm.provider :virtualbox do |vb|
    vb.name   = "lb-ubuntu-14_04-x64"
    vb.memory = 1024
    vb.cpus   = 4
  end
end
