Vagrant.configure("2") do |config|
  config.vm.box = "chef/centos-6.5"
  config.vm.hostname = "lb-centos-6-5-x64"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, host: 8080, guest: 80
  config.vm.provider :virtualbox do |vb|
    vb.name   = "lb-centos-6_5-x64"
    vb.memory = 1024
    vb.cpus   = 4
  end
end
