CLOUD_CONFIG_PATH = File.join(File.dirname(__FILE__), "user-data")

Vagrant.configure("2") do |config|
  config.vm.box      = "centos/atomic-host"
  config.vm.hostname = "lb-centos-7-atomic-vagrant"

  config.vm.provider :virtualbox do |vb|
    vb.name                  = "lb-centos-7-atomic-vagrant"
    vb.memory                = 1024
    vb.cpus                  = 4
    vb.check_guest_additions = false
    vb.functional_vboxsf     = false
    vb.gui                   = true
  end

  #if File.exist?(CLOUD_CONFIG_PATH)
  #  config.vm.provision :file, :source => "#{CLOUD_CONFIG_PATH}", :destination => "/tmp/vagrantfile-user-data"
  #  config.vm.provision :shell, :inline => "mv /tmp/vagrantfile-user-data /var/lib/cloud/instances/nocloud/", :privileged => true
  #end

end
