Vagrant.configure("2") do |config|
  config.vm.box = "chef/debian-7.8"
  config.vm.hostname = "lb-debian-7-8-x64"
  config.vm.provision :shell, path: "https://raw.githubusercontent.com/lburgazzoli/lb-devops/master/lb-vagrant/resources/bootstrap.sh"
  config.vm.provider :virtualbox do |vb|
    vb.name   = "lb-debian-7_8-x64"
    vb.memory = 1024
    vb.cpus   = 4
  end
end
