Vagrant.configure("2") do |config|
  config.vm.box = "chef/centos-7.0"
  config.vm.hostname = "lb-centos-7-0"
  config.vm.provision :shell, path: "https://raw.githubusercontent.com/lburgazzoli/lb-devops/master/lb-vagrant/resources/bootstrap.sh"
  config.vm.network :forwarded_port, host: 8080, guest: 80
  config.vm.provider :virtualbox do |vb|
    vb.name   = "lb-centos-7_0"
    vb.memory = 1024
    vb.cpus   = 4
  end
end
